spring.application.name=notification-service
spring.datasource.url=jdbc:mysql://localhost:3306/m4_config
spring.datasource.username=root
spring.datasource.password=r00t_3nj0y1n9_my$ql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
